"""empty message

Revision ID: e354892af84c
Revises: e5cbfa577206
Create Date: 2017-05-07 02:18:49.228805

"""

# revision identifiers, used by Alembic.
revision = 'e354892af84c'
down_revision = 'e5cbfa577206'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('task_id', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'task_id')
    # ### end Alembic commands ###
